version: "3.9"

services: 
    database:
        image: postgres 
        environment: 
            - POSTGRES_DB=pharmacy
            - POSTGRES_USER=postgres
            - POSTGRES_PASWORD=pharmacyPASS
        ports:
            - "5432:5432"
        volumes:
            - postgresdata:/var/lib/postgresql
volumes:
    postgresdata:
        external: true